export const timeZones = [
    { value: "UTC", label: "UTC - Coordinated Universal Time" },
    { value: "Africa/Lagos", label: "GMT+01:00 - West Africa Time (Africa/Lagos)" },
    { value: "Europe/Paris", label: "GMT+01:00 - Central European Time (Europe/Paris)" },
    { value: "Africa/Johannesburg", label: "GMT+02:00 - South Africa Standard Time (Africa/Johannesburg)" },
    { value: "Europe/Kaliningrad", label: "GMT+02:00 - Eastern European Time (Europe/Kaliningrad)" },
    { value: "Europe/Moscow", label: "GMT+03:00 - Moscow Standard Time (Europe/Moscow)" },
    { value: "Asia/Riyadh", label: "GMT+03:00 - Arabian Standard Time (Asia/Riyadh)" },
    { value: "Asia/Dubai", label: "GMT+04:00 - Gulf Standard Time (Asia/Dubai)" },
    { value: "Asia/Karachi", label: "GMT+05:00 - Pakistan Standard Time (Asia/Karachi)" },
    { value: "Asia/Dhaka", label: "GMT+06:00 - Bangladesh Standard Time (Asia/Dhaka)" },
    { value: "Asia/Bangkok", label: "GMT+07:00 - Indochina Time (Asia/Bangkok)" },
    { value: "Asia/Shanghai", label: "GMT+08:00 - China Standard Time (Asia/Shanghai)" },
    { value: "Asia/Tokyo", label: "GMT+09:00 - Japan Standard Time (Asia/Tokyo)" },
    { value: "Australia/Sydney", label: "GMT+10:00 - Australian Eastern Standard Time (Australia/Sydney)" },
    { value: "Pacific/Auckland", label: "GMT+12:00 - New Zealand Standard Time (Pacific/Auckland)" },
    { value: "Atlantic/Azores", label: "GMT-01:00 - Azores Standard Time (Atlantic/Azores)" },
    { value: "America/Noronha", label: "GMT-02:00 - Fernando de Noronha Time (America/Noronha)" },
    { value: "America/Sao_Paulo", label: "GMT-03:00 - Brasília Time (America/Sao_Paulo)" },
    { value: "America/Caracas", label: "GMT-04:00 - Venezuela Time (America/Caracas)" },
    { value: "America/New_York", label: "GMT-05:00 - Eastern Standard Time (America/New_York)" },
    { value: "America/Chicago", label: "GMT-06:00 - Central Standard Time (America/Chicago)" },
    { value: "America/Denver", label: "GMT-07:00 - Mountain Standard Time (America/Denver)" },
    { value: "America/Los_Angeles", label: "GMT-08:00 - Pacific Standard Time (America/Los_Angeles)" },
    { value: "America/Anchorage", label: "GMT-09:00 - Alaska Standard Time (America/Anchorage)" },
    { value: "Pacific/Honolulu", label: "GMT-10:00 - Hawaii-Aleutian Standard Time (Pacific/Honolulu)" },
    { value: "Pacific/Midway", label: "GMT-11:00 - Midway Island Time (Pacific/Midway)" },
    { value: "Etc/GMT-12", label: "GMT-12:00 - International Date Line West (Etc/GMT-12)" }
];
 